sudo: required
dist: trusty

language: node_js

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

before_script:
  - npm run build
  - npm run test-server &

script:
  - npm test